KnockoutSeatReservation/Models/SeatReservation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KnockoutSeatReservation.Models
{
    public class SeatReservation
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int MealId { get; set; }

        public Meal Meal { get; set; }
    }
}

KnockoutSeatReservation/Controllers/MealsController.cs
using KnockoutSeatReservation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnockoutSeatReservation.Controllers
{
    public class MealsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Meals
        public JsonResult GetAllMeals()
        {
            var x = db.Meals.ToList();
            return Json(x, JsonRequestBehavior.AllowGet);
        }
    }
}

KnockoutSeatReservation/Controllers/SeatReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KnockoutSeatReservation.Models;

namespace KnockoutSeatReservation.Controllers
{
    public class SeatReservationsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: SeatReservations
        public ActionResult Index()
        {
            var seatReservations = db.SeatReservations.Include(s => s.Meal);
            return View(seatReservations.ToList());
        }

        // GET: SeatReservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SeatReservation seatReservation = db.SeatReservations.Find(id);
            if (seatReservation == null)
            {
                return HttpNotFound();
            }
            return View(seatReservation);
        }

        // GET: SeatReservations/Create
        public ActionResult Create()
        {
            ViewBag.MealId = new SelectList(db.Meals, "Id", "Name");
            return View();
        }

        // POST: SeatReservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,MealId")] SeatReservation seatReservation)
        {
            if (ModelState.IsValid)
            {
                db.SeatReservations.Add(seatReservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MealId = new SelectList(db.Meals, "Id", "Name", seatReservation.MealId);
            return View(seatReservation);
        }

        // GET: SeatReservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SeatReservation seatReservation = db.SeatReservations.Find(id);
            if (seatReservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.MealId = new SelectList(db.Meals, "Id", "Name", seatReservation.MealId);
            return View(seatReservation);
        }

        // POST: SeatReservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,MealId")] SeatReservation seatReservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seatReservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MealId = new SelectList(db.Meals, "Id", "Name", seatReservation.MealId);
            return View(seatReservation);
        }

        // GET: SeatReservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SeatReservation seatReservation = db.SeatReservations.Find(id);
            if (seatReservation == null)
            {
                return HttpNotFound();
            }
            return View(seatReservation);
        }

        // POST: SeatReservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SeatReservation seatReservation = db.SeatReservations.Find(id);
            db.SeatReservations.Remove(seatReservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KnockoutSeatReservation/Views/SeatReservations/Create.cshtml
@model KnockoutSeatReservation.Models.SeatReservation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SeatReservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MealId, "MealId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MealId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MealId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KnockoutSeatReservation/Views/SeatReservations/Delete.cshtml
@model KnockoutSeatReservation.Models.SeatReservation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SeatReservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Meal.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meal.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KnockoutSeatReservation/Views/SeatReservations/Details.cshtml
@model KnockoutSeatReservation.Models.SeatReservation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SeatReservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Meal.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meal.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KnockoutSeatReservation/Views/SeatReservations/Edit.cshtml
@model KnockoutSeatReservation.Models.SeatReservation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SeatReservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MealId, "MealId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MealId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MealId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KnockoutSeatReservation/Views/SeatReservations/Index.cshtml
@model IEnumerable<KnockoutSeatReservation.Models.SeatReservation>

@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>*@

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Meal.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Meal.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>*@













<h2>Your seat reservations (<span data-bind="text: seats().length"></span>)</h2>

<table>
    <thead>
        <tr>
            <th>Passenger name</th>
            <th>Meal</th>
            <th>Surcharge</th>
            <th></th>
        </tr>
    </thead>
    <tbody data-bind="foreach: seats">
        <tr>
            <td><input data-bind="value: name" /></td>
            <td><select data-bind="options: $root.availableMeals, value: meal, optionsText: 'Name'"></select></td>
            <td data-bind="text: formattedPrice"></td>
            <td><a href="#" data-bind="click: $root.removeSeat">Remove</a></td>
        </tr>
    </tbody>
</table>

<button data-bind="click: addSeat, enable: seats().length < 5">Reserve another seat</button>

<h3 data-bind="visible: totalSurcharge() > 0">
    Total surcharge: $<span data-bind="text: totalSurcharge().toFixed(2)"></span>
</h3>




@section scripts{
<script src="~/Scripts/knockout-3.4.0.js"></script>
<script>
    $(function () {

        $.getJSON("@Url.Action("GetAllMeals","Meals")").done(function (data) {

            var model = new ReservationsViewModel(data);
            ko.applyBindings(model);

        });
    })

    // Class to represent a row in the seat reservations grid
    function SeatReservation(name, initialMeal) {

        this.name = name;
        this.meal = ko.observable(initialMeal);

        this.formattedPrice = ko.computed(function () {
            var price = this.meal().Price;
            return price ? "$" + price.toFixed(2) : "None";
        }, this);
    }

    // Overall viewmodel for this screen, along with initial state
    function ReservationsViewModel(meals) {

        //var self = this;
        this.availableMeals = meals;


        // Editable data
        this.seats = ko.observableArray([
            new SeatReservation("Steve", this.availableMeals[0]),
            new SeatReservation("Bert", this.availableMeals[2])
        ]);

        // Computed data
        this.totalSurcharge = ko.computed(function () {
            var total = 0;
            for (var i = 0; i < this.seats().length; i++) {
                total += this.seats()[i].meal().Price;
            }
            return total;
        }, this);

        // Operations
        this.addSeat = function () {
            this.seats.push(new SeatReservation("", this.availableMeals[0]));
        }

        //var self = this;
        //self.seats.remove(...)
        //bind is needed because context of this is different when called from $root or any other binding context like $parent
        this.removeSeat = function (seat) { this.seats.remove(seat) }.bind(this);
    }

</script>
}